export const recipes = [
  {
    id: 997,
    categories: "Tatlı",
    title: "Tatlı Dilek",
    explanation: "Masterchef Türkiye'de Mehmet Şef'in imza tabağı  Tatlı Dilek",
    longDescription:
      "Masterchef Türkiye'de Mehmet Şef'in imza tabağı olan tatlı dilek yapımında, krem fontana ve sifon kek kullanılır. Tatlının üzerinde birbirinden farklı meyveler kullanılır. Malzemeler hazırsa, Mehmet Şef'ten tatlı dilek tarifi için detaylara geçebiliriz.",
    img: "https://res.cloudinary.com/dd4d48hwn/image/upload/v1680771689/tatl%C4%B1dilek_ee1905.jpg",
    manyPerson: "2",
    preparaTiontime: "20",
    cookingTime: "40",
    shareRecipe: [
      {
        name: "Mehmet ASLANTAŞ",
        membershipStatus: "Founder",
        email: "mehmetaslantas@mizanplas.net",
        image:
          "https://res.cloudinary.com/dd4d48hwn/image/upload/v1682791174/mehmetaslanta%C5%9F_aojjvf.jpg",
      },
    ],
    materials: [
      "Limon",
      "Bal",
      "Toz şeker",
      "Granül kahve",
      "Kestane şekeri",

      "Taze fesleğen",
      "Bal",
      "Kestane şekeri",

      "30 gr un",
      "Tuz",
      "Mürekkep balığı mürekkebi",
      "220 gr beyaz pralin",
      "180 gr yumurta beyazı",
      "Bronz toz boya",

      "Yağ bazlı siyah gıda boyası",
      "Kakao yağı",
      "Dekor jelatini",
      "Beyaz para çikolata",
      ,
      "Böğürtlen",
      "Frenk üzümü",
      "Frambuaz",
      "Altın çilek",
      "Kumkuat",
    ],
    preparation: [
      "Krem fontana için; Tencereye süt, krema, rendelenmiş zencefil ve vanilya çubuğunu ekleyerek sürekli karıştırın ve kaynatın.",
      "Başka bir tencerede yumurta sarısı ve toz şekeri karıştırarak ılıtın. Ama kaynatmayın.",
      "Ilıyan yumurta sarısının için, diğer karışımı yavaş yavaş karıştırarak ekleyin.",
      "Suda beklettiğiniz yaprak jelatinleri de ekleyin ve karıştırın.",
      "Krem fontanayı, 2 ayrı karıştırma kabına paylaştırın.",
      "Başka bir tavada toz şeker ile karamel yapın. İçine bal ekleyerek biraz soğutun.",
      "Kaplardan birinde olan krem fontanaya ballı karışımı ve granül kahveyi ekleyerek karıştırın.",
      "Bu karışımı bardakların tabanına eşit miktarda paylaştırarak soğutucuya atarak dondurun.",
      "Alt kısmı donduktan sonra, zencefilli krem fontanayı eşit miktarda üzerine ekleyin ve dondurun.",
      "Kestane sosu için; Tavaya kestane şekerini alın. Kaşık ile ezin. Üzerine bal ve kremayı ekleyip kaynatın.",
      "Fesleğen yapraklarını ince ince doğrayıp içine ilave edin. İyice kaynayan ve kıvam alan sosu, ocaktan alın ve soğuması için bir süre bekleyin.",
      "Donmuş krem fontanaların üzerine bu karışımı ekleyin ve tekrar dondurucuya atın.",
      "Sifon kek için; Beyaz pralin, un, tuz, yumurta beyazı ve mürekkep balığı mürekkebini alarak iyice köpürene kadar çırpın.",
      "Sifonun içerisine doldurup kapağını kapatın ve 2 tane gaz tüpünü içerisine doldurun. Karton bardaklara sıkarak mikrodalgada 40 saniye-1 dakika arası pişirin.",
      "Bardakları kestikten sonra kekleri içinden çıkartın. Üzerini bronz toz boya ile kaplayın.",
      "Çikolata dekoru için; Kakao yağını eritin ve siyah gıda boyası ile karıştırın.",
      "Karıştırarak soğutun ve dekor jelatinin üzerine yayarak donmaya bırakın.",
      "Beyaz para çikolatalarını eritin. Dekor jelatinin üzerine ince bir tabaka halinde yayın. Bardağın üzerini kapatacak boyda bir çember ile çikolataları kesin.",
      "Krem fontanayı dolaptan çıkartın. Cımbız yardımıyla sifon keki orta kısma yerleştirin.",
    ],
  },
  {
    id: 998,
    categories: "Ana Yemek",
    title: "Taş Havuz",
    explanation: "Masterchef Türkiye'de, Somer Şef'in imza tabağı  Taş Havuz",
    longDescription:
      "Kıbrıs'ın sevilen lezzetlerinden birini sizlerle paylaşmak isteriz. Şeftali kebabı Kıbrıs'a ait bir kebaptır. Koyun veya keçinin gömlek yağından yapılır. Gömlek yağının içerisine kıymalı harç koyularak pişirilir. Şişte veya ızgarada pişirilmesi önerilir. Malzemeler hazırsa, Kıbrıs usulü şeftali kebabı tarifine geçebiliriz.",
    img: "https://res.cloudinary.com/dd4d48hwn/image/upload/v1680771690/ta%C5%9Fhavuz_i9qcik.jpg",
    manyPerson: "2",
    preparaTiontime: "25",
    cookingTime: "40",
    shareRecipe: [
      {
        name: "Mustafa ASLANTAŞ",
        membershipStatus: "Founder",
        email: "mustafataslantas@mizanplas.net",
        image: "",
      },
    ],
    materials: [
      "Zeytinyağı",
      "Köz kömür",
      "Siyah midye",
      "Mürekkep",
      "Ayçiçek yağı",
      "Pirinç kağıdı",
      "Agar agar",
      "Nar",
      "Sarımsak",
      "Sazan yumurtası",
      "Deniz tuzu",
      "Arpacık soğan",
      "Üzüm çekirdeği yağı",
      "Buz",
      "Limon",
      "Portakal",
      "Kerevit",
      "Frank soğan",
      "Chili biber",
      "Tuz",
      "Biberiye",
      "Deniz tarağı",
      "Kakao yağı",
      "Miso",
      "Patlıcan",
      "Karnabahar",
      "Sirke",
      "Pancar",
    ],
    preparation: [
      "Deniz börülcelerini blanch edin ve kılçıklarını temizleyin.",
      "Pirinç cipsine mürekkep sürün ve kızartın.",
      "İsli midye için; Zeytinyağını bir kaba doldurun. İçine daha küçük bir kap koyun ve blanch edilmiş isli midyeyi ekleyin. Yağın içine közlenmiş kömür parçası ekleyin. İki kap iç içe olacak şekilde streçleyin. 20 dakika bu şekilde bekletin.",
      "Cips için; Fırça yardımıyla kalamar mürekkebi pirinç yaprağına sürün. Daha sonra kızartın.",
      "Nar havyarı için; Taze sıkılmış nar suyunu 100 dereceye getirin. Agar agar ekleyerek kıvam verin. Soğuk zeytinyağına donmadan hızlı bir şekilde, bir şırınga yardımıyla dökün.",
      "Tarama için; Tüm malzemeler miksere alın ve karıştırın. Ürün kıvam alınca, limon suyu ve buzlu su damlatılarak istenen kıvama ulaşın.",
      "Deniz tarağı için; Bir tavanın içinde önce kakao yağını eritin. Daha sonra diğer malzemeleri ilave ederek deniz tarağını kızartın.",
      "Misolu patlıcan için; Patlıcan ve sarımsakları közleyin. Közlendikten sonra içine miso ekleyin ve blenderdan geçirin.",
      "Mercan için; Karnabaharı yuvarlak şekilde kesin. Pancar, sirke ve tuz ekleyip haşlayın. Ardından suyunu süzüp buzlu su içine alın.",
      "Ceviche için; Tüm malzemeleri ufak ufak kesin. Limon ve portakal suyunda bekletin.",
      "Tabağın alt kısmını midye kabuklarıyla doldurun. Üzerine deniz tarağının kabuklarını koyun.  ",
      " Kabukların içine miso patlıcan, deniz tarağı ve nar havyarı ekleyin.",
      "Mısır patlaklarını da tabağa alın ve üzerine isli midyeleri ilave edin. Kerevitin sırtına ceviche doldurun.",
      "Tabağın ortasına yerleştirin. Belirli noktalara tarama sıkın ve otlarla süsleyin.",
    ],
  },
  {
    id: 999,
    categories: "Ana Yemek",
    title: "Şeftali Kebabı",
    explanation:
      "Kıbrıs'ın sevilen lezzetlerinden birini sizlerle paylaşmak isteriz. Şeftali Kebabı ",
    longDescription:
      "Kıbrıs'ın sevilen lezzetlerinden birini sizlerle paylaşmak isteriz. Şeftali kebabı Kıbrıs'a ait bir kebaptır. Koyun veya keçinin gömlek yağından yapılır. Gömlek yağının içerisine kıymalı harç koyularak pişirilir. Şişte veya ızgarada pişirilmesi önerilir. Malzemeler hazırsa, Kıbrıs usulü şeftali kebabı tarifine geçebiliriz.",
    img: "https://res.cloudinary.com/dd4d48hwn/image/upload/v1680771690/seftalikebab%C4%B1_xg0vov.jpg",
    manyPerson: "5",
    preparaTiontime: "15",
    cookingTime: "30",
    shareRecipe: [
      {
        name: "Mehmet ASLANTAŞ",
        membershipStatus: "Founder",
        email: "mehmetaslantas@mizanplas.net",
        image:
          "https://res.cloudinary.com/dd4d48hwn/image/upload/v1682791174/mehmetaslanta%C5%9F_aojjvf.jpg",
      },
    ],
    materials: [
      "300 gr yağsız kıyma ",
      "Gömlek Yağı ",
      "1 adet soğan ",
      "4-5 dal maydanoz ",
      "2-3 yemek kaşığı galeta unu ",
      "1 çay kaşığı kimyon ",
      "1 çay kaşığı tuz",
      "1 çay kaşığı karabiber",
    ],
    preparation: [
      "Soğanı rendeleyin. Fazla suyunu sıkarak bir kaba alın. ",
      "Maydanozu ince ince doğrayın ve soğanın yanına ekleyin.",
      "Galeta unu ve baharatları ilave edin. ",
      "Kıyma ile birlikte yoğurun. ",
      "Yıkanan ve temizlenen gömlek yağından parçaları tezgaha serin. ",
      "Köfteleri porsiyonladıktan sonra gömlek yağının içerisine sarın. ",
      "Izgarada ya da şişte pişirin. Afiyet olsun. ",
    ],
  },
  {
    id: 1000,
    categories: "Meze",
    title: "Uskumru Tarator",
    explanation:
      "Füme uskumru ve krema'nın eşşiz uyumu ile hazırlanan uskumru tarator, balık sevmeyenleri bile kendine hayran bırakacak bir mezedir.",
    longDescription:
      "Füme uskumru ve krema ile hazırlanan uskumru tarator, balık sevmeyenleri bile kendine hayran bırakacak bir mezedir. Yemeklerin yanında sunabileceğiniz bu meze, ortalama 30 dakikada hazırlanır. Tarifte kullanacağınız uskumrunun, tamamen kılçıksız olması gerekir. Malzemeler hazırsa, uskumru tarator yapımına geçebiliriz.",
    img: "https://res.cloudinary.com/dd4d48hwn/image/upload/v1680771689/uskumrutarator_tujhcg.jpg",
    manyPerson: "4",
    preparaTiontime: "15",
    cookingTime: "15",
    shareRecipe: [
      {
        name: "Mehmet ASLANTAŞ",
        membershipStatus: "Founder",
        email: "mehmetaslantas@mizanplas.net",
        image:
          "https://res.cloudinary.com/dd4d48hwn/image/upload/v1682791174/mehmetaslanta%C5%9F_aojjvf.jpg",
      },
    ],
    materials: [
      "250 gram füme uskumru",
      "4 yemek kaşığı çiğ krema ",
      "Yarım limonun suyu",
      "1 adet orta boy soğan ",
      "2 yemek kaşığı zeytinyağı",
      "Yeterince beyaz toz biber",
    ],
    preparation: [
      "Füme uskumruların kılçıklarını temizleyin. ",
      "Soğanı ince ince doğrayın. Zeytinyağı ile birlikte karamelize edin.",
      "Bir karıştırma kabına soğan dışında bütün malzemeleri ekleyin ve blenderdan geçirin.",
      "Püre haline gelmiş tarator üzerine karamelize soğan eklenerek servis edilir. Afiyet olsun. ",
    ],
  },
  {
    id: 1001,
    categories: "Çorba",
    title: "Mercimek Çorbası",
    explanation:
      "Türk mutfağının vazgeçilmezlerinden birisi olan, lezzetli ve besleyici bir çorba olan mercimek çorbası.",
    longDescription:
      "Kırmızı mercimek, soğan, sarımsak, havuç ve patates gibi malzemelerle zenginleştirilen bu çorba, hem kolay hazırlanır hem de doyurucu bir öğün sunar. Mercimeklerin püre kıvamına gelene kadar pişirildiği bu tarif, sıcak servis edildiğinde hem gözleri hem de mideleri mutlu eder. Limon dilimleri ve taze maydanozla servis edilerek çorbaya tazelik ve ferahlık katılır. Hem pratik hem de lezzetli bir çorba arayanlar için ideal bir seçenektir.",
    img: "https://res.cloudinary.com/dd4d48hwn/image/upload/v1684358724/Ads%C4%B1z_tasar%C4%B1m_10_cbeaur.png",
    manyPerson: "4",
    preparaTiontime: "10",
    cookingTime: "30",
    shareRecipe: [
      {
        name: "Mehmet ASLANTAŞ",
        membershipStatus: "Founder",
        email: "mehmetaslantas@mizanplas.net",
        image:
          "https://res.cloudinary.com/dd4d48hwn/image/upload/v1682791174/mehmetaslanta%C5%9F_aojjvf.jpg",
      },
    ],
    materials: [
      "1 su bardağı kırmızı mercimek",
      "1 adet soğan",
      "2 diş sarımsak",
      "1 yemek kaşığı domates salçası",
      "6 su bardağı su",
      "1 yemek kaşığı tereyağı veya sıvı yağ",
      "1 çay kaşığı kırmızı biber",
      "1 çay kaşığı kimyon",
      "Tuz",
      "Karabiber",
      "Limon dilimleri ve maydanoz yaprakları (servis için)",
    ],
    preparation: [
      "Mercimeği yıkayıp süzün.",
      "Soğanı doğrayın, sarımsakları ezin.",
      "Tencerede tereyağı veya sıvı yağı eritin.",
      "Soğanları ve sarımsakları ekleyip pembeleşene kadar kavurun.",
      "Domates salçasını ekleyip kısa bir süre daha kavurun.",
      "Yıkanmış mercimekleri tencereye ekleyin ve karıştırın.",
      "Su, tuz, karabiber, kimyon ve kırmızı biberi ekleyin.",
      "Tencerenin kapağını kapatın ve mercimekler yumuşayana kadar orta ateşte pişirin (yaklaşık 25-30 dakika).",
      "Pişen çorbayı blendır veya çatalla püre haline getirin.",
      "Servis yaparken üzerine limon dilimleri ve maydanoz yaprakları ekleyebilirsiniz.",
    ],
  },
  {
    id: 1002,
    categories: "Pilav & Makarna",
    title: "Mısırlı Pirinç Pilavı",
    explanation:
      "Özellikle Et ve Tavuk Yemekleri yanında vazgeçilmez lezzet, Mısırlı Pirinç Pilavı",
    longDescription:
      "Özellikle Et ve Tavuk Yemeklerinin vazgeçilmezi mısırlı pirinç pilavı. Konserve olarak alınan veya taneleri ayıklanan mısır, pirinç pilavına lezzet katan besinler arasında yer alır Kısa sürede hazırlayarak sofarnızın baş köşesine koyacağınız vazgeçilmez lezzet.",
    img: "https://res.cloudinary.com/dd4d48hwn/image/upload/v1684358724/Ads%C4%B1z_tasar%C4%B1m_11_gjbw5i.png",
    manyPerson: "6",
    preparaTiontime: "10",
    cookingTime: "15",
    shareRecipe: [
      {
        name: "Mehmet ASLANTAŞ",
        membershipStatus: "Founder",
        email: "mehmetaslantas@mizanplas.net",
        image:
          "https://res.cloudinary.com/dd4d48hwn/image/upload/v1682791174/mehmetaslanta%C5%9F_aojjvf.jpg",
      },
    ],
    materials: [
      "2 su bardağı pirinç",
      "3 su bardağı tavuk suyu",
      "1 kase haşlanmış mısır",
      "Tereyağı",
      "Kestane şekeri",
      "Sıvı yağ",
      "Tuz",
    ],
    preparation: [
      "Pirinçleri sıcak tuzlu suda bir saat bekletelim. Süzdürdükten sonra soğuk su ile iyice yıkayalım.",
      "Tenceremize sıvı yağ ve tereyağı koyalım. İyice yıkanmış pirinçleri içine katıp 5 dk kavuralım..",
      "Mısırları da katıp bir iki dk daha kavuralım. Tuzunu katalım.",
      "3 su bardağı tavuk suyunu döküp iyice kaynadıktan sonra altını kısıp kapağını kapatalım. Suyunu çekene kadar pişirelim. Demlendirip servis edelim. Afiyet olsun",
    ],
  },
  {
    id: 1003,
    categories: "Ana Yemek",
    title: "Patateli Havuçlu Etli Güveç",
    explanation:
      "Enfes bir lezzet deneyimi sunan geleneksel bir lezzet, Patatesli Havuçlu Etli Güveç",
    longDescription:
      "Patatesli Havuçlu Etli Güveç, enfes bir lezzet deneyimi sunan geleneksel bir yemektir. Bu tarifte, mükemmel uyum sağlayan dana eti, patates, havuç ve baharatlar bir araya gelerek muhteşem bir güveç oluşturuyor. Etlerin özenle kavrulduğu, sebzelerin yumuşak ve aromatik olduğu bu güveç, lezzet avcılarının favorisi haline gelmeye aday. Sıcak ve doyurucu bu yemek, misafirlerinizi ve sevdiklerinizi şımartmanın harika bir yoludur. Hem hazırlaması kolay hem de sunumu göz alıcı olan Patatesli Havuçlu Etli Güveç, sofralarınıza lezzet ve keyif katmak için ideal bir seçenektir.",
    img: "https://res.cloudinary.com/dd4d48hwn/image/upload/v1684306145/Ads%C4%B1z_tasar%C4%B1m_9_rzcq3n.png",
    manyPerson: "4",
    preparaTiontime: "30",
    cookingTime: "80",
    shareRecipe: [
      {
        name: "Mehmet ASLANTAŞ",
        membershipStatus: "Founder",
        email: "mehmetaslantas@mizanplas.net",
        image:
          "https://res.cloudinary.com/dd4d48hwn/image/upload/v1682791174/mehmetaslanta%C5%9F_aojjvf.jpg",
      },
    ],
    materials: [
      "500 gram dana eti (kuşbaşı şeklinde)",
      "2 adet büyük boy patates (küp doğranmış)",
      "2 adet havuç (halka şeklinde dilimlenmiş)",
      "1 adet soğan (yemeklik doğranmış)",
      "3 diş sarımsak (ezilmiş)",
      "2 yemek kaşığı domates salçası",
      "2 su bardağı sıcak su",
      "2 yemek kaşığı sıvı yağ",
      "1 çay kaşığı pul biber",
      "1 çay kaşığı kekik",
      "Tuz",
      "Karabiber",
    ],
    preparation: [
      "Bir tencereye sıvı yağı ekleyin ve ısıtın.",
      "Kuşbaşı doğranmış dana etini ekleyin ve suyunu salıp çekene kadar kavurun.",
      "Doğranmış soğanı ve ezilmiş sarımsağı ekleyin. Soğanlar pembeleşene kadar kavurun.",
      "Domates salçasını ekleyin ve kavurmaya devam edin.",
      "Patatesleri ve havuç dilimlerini ekleyin. Birkaç dakika karıştırarak kavurun.",
      "Sıcak suyu ekleyin ve karıştırın.",
      "Tuz, karabiber, pul biber ve kekiği ekleyin. Karıştırarak kaynamaya bırakın.",
      "Kaynadıktan sonra ateşi kısın ve güvecin kapağını kapatın.",
      "Etler ve sebzeler yumuşayıncaya kadar, yaklaşık 1 saat pişirin.",
      "Sıcak olarak servis yapın.",
    ],
  },
  {
    id: 1004,
    categories: "Tatlı",
    title: "Fırında Sütlaç",
    explanation:
      "Türk mutfağının sevilen tatlılarından, kremsi ve pürüzsüz bir kıvama sahip olan Fırında Sütlaç",
    longDescription:
      "Fırında Sütlaç, Türk mutfağının en sevilen ve geleneksel tatlılarından biridir. Kremsi dokusu ve lezzetli vanilya aromasıyla, birçok kişinin favori tatlılarından biridir. Fırında pişirilerek elde edilen altın rengi üst tabakasıyla da görsel olarak oldukça çekici bir görünüme sahiptir. ",
    img: "https://res.cloudinary.com/dd4d48hwn/image/upload/v1684306145/Ads%C4%B1z_tasar%C4%B1m_8_i9eik8.png",
    manyPerson: "4-6",
    preparaTiontime: "15",
    cookingTime: "30-40",
    shareRecipe: [
      {
        name: "Mehmet ASLANTAŞ",
        membershipStatus: "Founder",
        email: "mehmetaslantas@mizanplas.net",
        image:
          "https://res.cloudinary.com/dd4d48hwn/image/upload/v1682791174/mehmetaslanta%C5%9F_aojjvf.jpg",
      },
    ],
    materials: [
      "1 litre süt",
      "1 su bardağı toz şeker",
      "Yarım su bardağı pirinç",
      "2 yemek kaşığı pirinç unu",
      "1 tatlı kaşığı vanilya özütü",
      "1 çay kaşığı rendelenmiş limon kabuğu",
      "1 çay kaşığı tarçın (isteğe bağlı)",
      "2 yemek kaşığı tereyağı (eritilmiş)",
      "1 çay kaşığı tuz",
      "3 adet yumurta sarısı",
      "1 yemek kaşığı nişasta (isteğe bağlı)",
    ],
    preparation: [
      "Fırını 180 dereceye ayarlayın ve ısıtmaya başlayın.",
      "Bir tencereye sütü ekleyin ve orta ateşte ısıtın. Süt kaynamaya başladığında altını kısın.",
      "Ayrı bir kapta pirinci yıkayın ve süzün.",
      "Yıkanmış pirinci kaynar sütün içine ekleyin. Karıştırarak pirinçlerin yumuşamasını sağlayın. Arada karıştırarak, yaklaşık 15-20 dakika pişirin.",
      "Toz şekeri ekleyin ve karıştırarak eritin.",
      "Pirinçler iyice piştiğinde tencereyi ocaktan alın.",
      "Pirinç ununu, vanilya özütünü, rendelenmiş limon kabuğunu, tarçını (isteğe bağlı), eritilmiş tereyağını ve tuzu ekleyin. Karıştırarak tüm malzemelerin iyice birleşmesini sağlayın.",
      "Yumurta sarılarını ekleyin ve hızlıca karıştırın. Bu aşamada nişasta kullanmak isterseniz, nişastayı da ekleyin ve karıştırmaya devam edin.",
      "Karışımı fırın kabına dökün. Üzerini düzleştirerek pürüzsüz bir görünüm elde edin.",
      "Fırın kabını, önceden ısıttığınız 180 derece fırında yaklaşık 30-40 dakika pişirin. Sütlaç, üstü hafif kızarana ve kıvamı iyice yoğunlaşana kadar pişmeye devam etmelidir.",
      "Pişen sütlaçları fırından çıkarın ve oda sıcaklığına gelmesini bekleyin.",
      "Oda sıcaklığına geldikten sonra sütlaçları buzdolabına kaldırın ve iyice soğuması için birkaç saat bekletin.",
      "Servis yapmadan önce üzerini tarçın veya hindistan cevizi ile süsleyebilirsiniz.",
    ],
  },
];
export default recipes;
